FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 5127

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Development
WORKDIR /src
COPY ["AuthServiceApp.API/AuthServiceApp.API.csproj", "AuthServiceApp.API/"]
RUN dotnet restore "AuthServiceApp.API/AuthServiceApp.API.csproj"
COPY . .
WORKDIR "/src/AuthServiceApp.API"
RUN dotnet build "./AuthServiceApp.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Development
RUN dotnet publish "./AuthServiceApp.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AuthServiceApp.API.dll"]