version: '3.8'

services:
  db:
    container_name: devops_auth_service_database_tests
    image: postgres:latest
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres