version: '3.8'

services:
  auth_service:
    container_name: devops_auth_service_development
    build:
      context: .
      dockerfile: Dockerfile.development  
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Database: Host=db;Port=5432;Database=devops_authservice;Username=postgres;Password=postgres
      ConnectionStrings__TestsDatabase: Host=db;Port=5432;Database=devops_authservice_tests;Username=postgres;Password=postgres
    ports:
      - "5127:8080"
    depends_on:
      - db
      
  db:
    container_name: devops_database_development
    image: postgres:latest
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:    