worker_processes 4;

events { worker_connections 1024; }

http {
	server {
		listen 80;

		location / {
			proxy_pass http://client:4173;
		}

		location /api {
			proxy_pass http://backend:8080;
		}

		location /swagger {
			proxy_pass http://backend:8080/swagger;
		}

		location /openapi/v1.json {
			proxy_pass http://backend:8080/openapi/v1.json;
		}
	}
}